# Generated by Django 5.0.3 on 2024-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=100)),
                ('codigo_pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
