# Generated by Django 5.0.3 on 2024-05-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentapp', '0002_constructora'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructora',
            name='contra',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constructora',
            name='correo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constructora',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
