# Generated by Django 5.0.3 on 2024-05-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentapp', '0003_constructora_contra_constructora_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructora',
            old_name='contra',
            new_name='contraseña',
        ),
        migrations.AlterField(
            model_name='constructora',
            name='correo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
