# Generated by Django 5.0.3 on 2024-05-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentapp', '0004_rename_contra_constructora_contraseña_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constructora',
        ),
    ]
