# Generated by Django 5.0.3 on 2024-05-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='id_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeapp.proyecto'),
        ),
    ]
