# Generated by Django 5.0.2 on 2024-08-23 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentapp', '0001_initial'),
        ('homeapp', '0002_proyecto_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='constructora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentapp.constructora'),
        ),
    ]
